### ISSUE TITLE
Error : Processes or Resource is not a directory

### ISSUE THREAD

**Issue by Tantino** [teivah/TIBreview#1]
Hello,
The first sorry by my english.xD.
I am checking the tools and I have the first error. In my case the process it is not in the path Processes.

I have reviewed the code and I think that the line:

> _processes = listProcesses(context.getSource() + PATH_PROCESSES);_

 in the class ProcessProcessor.java you should update by  

> _processes = listProcesses(context.getSource() );_

Thanks and regards.

**Comment by teivah** [comment]
Hello,
No problem :) Can you please share with me first your execution command in order to check the JAR arguments?
Thanks

**Comment by Tantino** [comment]
Hello,

The execution is:

> java -Dlog4j.configuration=log4j.properties -jar tibreview-0.0.1-jar-with-dependencies.jar -r ./target/test-classes/tibrules.xml -c ./target/test-classes/config.properties -i project -s C:/temp/tibcoReview/REST_API.module -o pmd -t C:/temp

PFA for proyect example in this [link](https://drive.google.com/open?id=0B1IsFT6chZfDLUVLSktaa3h1QW8)

Thanks and regards.

**Comment by teivah** [comment]
I understand, that's simply because your project did not contain the /Processes folder. I made an evolution to check whether the folder exists or not. I just commited it and released it to the [0.0.2](https://github.com/teivah/TIBreview/releases/tag/0.02)

**Comment by Tantino** [comment]
The problem is that the folder  _/Processes_ it could change the name and exists. 
For example:
 I am from Spain and this folder name is _/Procesos_. Can not I use the aplication? The files _".bwp"_ exists in other folder that it is not  _/Processes_
The folder _/Resource_ has the same issue.

.

**Comment by teivah** [comment]
Oh okay got it, I thought it was just due to the fact that the folder did not exist.
In that case, I implemented your piece of advice by simply removing the _+PATH_PROCESS_ and _+PATH_RESOURCE_.

Release 0.0.3. Please let me know if it's fine for you.

**Comment by Tantino** [comment]
Fine.Fixed the Issue.
I am not a GURU in porgrammer but Could I participate to the project?

Thanks and regards.

**Comment by teivah** [comment]
Sure! I sent you an [invitation](https://github.com/teivah/TIBreview/invitations) for being a contributor.
I will initialize a Wiki page this week-end to list the next steps. Your participation (ideas, remarks etc...) will be welcome.
