### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Aravind07-RK** [teivah/TIBreview#8]
Hi,
I am trying to execute the following command,

java -Dlog4j.configuration=file:"log4.properties" -jar tibreview-0.0.1.jar -r tibrules.xml -c config.properties -i project -s C:/bw6workspaces/soapUI_Integration/SoapUITests_Integration -o pmd -t C:/output

but I get the following response.,

Error: Unable to access jarfile tibreview-0.0.1.jar

How exactly to configure and run the command. Where should I run this command on cmd., should I got to any specific file path and execute the command.

**Comment by teivah** [comment]
Hi,

This error means you did not provide the correct JAR location.

**Comment by Aravind07-RK** [comment]
Hi Teivah,

I am searching for the jar, but couldn't find it., How exactly should I
used this??

**Comment by teivah** [comment]
The JAR is not in the source code. It is packaged in the released zip.
