### ISSUE TITLE
If-Else Statements

### ISSUE THREAD

**Issue by edlegaspi** [teivah/TIBreview#9]
Hi, sorry I'm too lazy to find a way to message the contributors of this code. Just wanted to ask if there is a sample rule you can share that is using an if-else statement (ex. if ackMode > 0 then true() else false()).

Btw, great job you've done here. I think this would help a lot of TIBCO users that are implementing a code review process of some sort.

**Comment by teivah** [comment]
Thanks for the message, much appreciated.
Yes, you can do it according to the following structure:
```xml
<rule name="rulename" ruleset="ruleset"
	prority="5"
	description="description">
	<impl>
		<cond>
			<if>
				<xpath></xpath>
				<then>
					<xpath></xpath>
				</then>
			</if>
			<elseif>
				<xpath></xpath>
				<then>
					<xpath></xpath>
				</then>
			</elseif>
			<else>
				<then>
					<xpath></xpath>
				</then>
			</else>
		</cond>
	</impl>
</rule>
```

**Comment by edlegaspi** [comment]
Thanks a lot! 👍
